
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtoalvsdkniueklybhwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0b2FsdnNka25pdWVrbHliaHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTM3NjEsImV4cCI6MjA1ODc2OTc2MX0.MNJsRPmQ4R7lOtpv4_5blZkCGaJUGPaw1trpwIoGV24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
