// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcpmikvwukeghrhmidlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcG1pa3Z3dWtlZ2hyaG1pZGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODE2MzksImV4cCI6MjA1ODc1NzYzOX0.mONjMSik7wr5-nch0kJitmEOSIrdKj9R-Vi343wYIGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);